# Uncomment the next line to define a global platform for your project
 platform :ios, '11.4'

target 'CryptoCurrency' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoCurrency

  pod 'Charts'

  target 'CryptoCurrencyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoCurrencyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
